In [1]:
!pip install transformers
!pip install transformers datasets

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 5.3 MB 13.3 MB/s 
     |████████████████████████████████| 7.6 MB 39.7 MB/s 
     |████████████████████████████████| 163 kB 70.8 MB/s 
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 441 kB 5.9 MB/s 
     |████████████████████████████████| 212 kB 73.6 MB/s 
     |████████████████████████████████| 115 kB 71.4 MB/s 
     |████████████████████████████████| 127 kB 72.3 MB/s 
     |████████████████████████████████| 115 kB 63.8 MB/s 
  Attempting uninstall: urllib3
    Found existing installation: urllib3 1.24.3
    Uninstalling urllib3-1.24.3:
      Successfully uninstalled urllib3-1.24.3


In [2]:
import torch
import transformers
from transformers import AutoModelForSequenceClassification, AutoTokenizer

import torch
import transformers
from transformers import AutoModelForSequenceClassification, AutoTokenizer

In [3]:
batch_sentences = [
    "Doing data transformation allows us to further simplify our dataset and make it easy and simple to understand?",
    "The last line list the song in the ascending order of popularity for a given song",
    "merge the song and artist_name into one column, aggregated by number of time a particular song",
]

In [4]:
batch_sentences = [
    "Doing data transformation allows us to understand",
    "The last line list the song",
    "merge the song and artist_name",
]

Tokenizer

In [5]:
tokenizer = AutoTokenizer.from_pretrained('bert-base-cased')

Downloading:   0%|          | 0.00/29.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/570 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/213k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/436k [00:00<?, ?B/s]

In [6]:
encoded_inputs=tokenizer(batch_sentences)
encoded_inputs

{'input_ids': [[101, 27691, 2233, 9047, 3643, 1366, 1106, 2437, 102], [101, 1109, 1314, 1413, 2190, 1103, 1461, 102], [101, 14713, 1103, 1461, 1105, 2360, 168, 1271, 102]], 'token_type_ids': [[0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1]]}

Padding

Adding pads to match the seqeuce length to eqaul size

In [7]:
encoded_inputs=tokenizer(batch_sentences,padding=True)
encoded_inputs

{'input_ids': [[101, 27691, 2233, 9047, 3643, 1366, 1106, 2437, 102], [101, 1109, 1314, 1413, 2190, 1103, 1461, 102, 0], [101, 14713, 1103, 1461, 1105, 2360, 168, 1271, 102]], 'token_type_ids': [[0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 0], [1, 1, 1, 1, 1, 1, 1, 1, 1]]}

Truncation:

truncates and fix the size of sequence to same length for long sentences

In [8]:
encoded_inputs=tokenizer(batch_sentences,padding=True,truncation=True)
encoded_inputs

{'input_ids': [[101, 27691, 2233, 9047, 3643, 1366, 1106, 2437, 102], [101, 1109, 1314, 1413, 2190, 1103, 1461, 102, 0], [101, 14713, 1103, 1461, 1105, 2360, 168, 1271, 102]], 'token_type_ids': [[0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 0], [1, 1, 1, 1, 1, 1, 1, 1, 1]]}

return_tensors:

return encode as pytorch tensors

In [9]:
encoded_inputs=tokenizer(batch_sentences,padding=True,truncation=True,return_tensors='pt')
encoded_inputs

{'input_ids': tensor([[  101, 27691,  2233,  9047,  3643,  1366,  1106,  2437,   102],
        [  101,  1109,  1314,  1413,  2190,  1103,  1461,   102,     0],
        [  101, 14713,  1103,  1461,  1105,  2360,   168,  1271,   102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1]])}

return_tensors:

return encode as tf tensors

In [10]:
encoded_inputs=tokenizer(batch_sentences,padding=True,truncation=True,return_tensors='tf')
encoded_inputs

{'input_ids': <tf.Tensor: shape=(3, 9), dtype=int32, numpy=
array([[  101, 27691,  2233,  9047,  3643,  1366,  1106,  2437,   102],
       [  101,  1109,  1314,  1413,  2190,  1103,  1461,   102,     0],
       [  101, 14713,  1103,  1461,  1105,  2360,   168,  1271,   102]],
      dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(3, 9), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(3, 9), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int32)>}

Loading yelp review dataset from transformer datsets

In [11]:
from datasets import load_dataset

dataset = load_dataset("yelp_review_full")


Generating train split:   0%|          | 0/650000 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/50000 [00:00<?, ? examples/s]

Dataset yelp_review_full downloaded and prepared to /root/.cache/huggingface/datasets/yelp_review_full/yelp_review_full/1.0.0/e8e18e19d7be9e75642fc66b198abadb116f73599ec89a69ba5dd8d1e57ba0bf. Subsequent calls will reuse this data.


  0%|          | 0/2 [00:00<?, ?it/s]

In [12]:
dataset['train']

Dataset({
    features: ['label', 'text'],
    num_rows: 650000
})

In [13]:
dataset["train"][100]

{'label': 0,
 'text': 'My expectations for McDonalds are t rarely high. But for one to still fail so spectacularly...that takes something special!\\nThe cashier took my friends\'s order, then promptly ignored me. I had to force myself in front of a cashier who opened his register to wait on the person BEHIND me. I waited over five minutes for a gigantic order that included precisely one kid\'s meal. After watching two people who ordered after me be handed their food, I asked where mine was. The manager started yelling at the cashiers for \\"serving off their orders\\" when they didn\'t have their food. But neither cashier was anywhere near those controls, and the manager was the one serving food to customers and clearing the boards.\\nThe manager was rude when giving me my order. She didn\'t make sure that I had everything ON MY RECEIPT, and never even had the decency to apologize that I felt I was getting poor service.\\nI\'ve eaten at various McDonalds restaurants for over 30 years. 

In [14]:
tokenizer

PreTrainedTokenizerFast(name_or_path='bert-base-cased', vocab_size=28996, model_max_len=512, is_fast=True, padding_side='right', truncation_side='right', special_tokens={'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]'})

function to tokenize the text data using automodel

In [15]:
def tokenize_function(description):
  return tokenizer(description['text'],padding='max_length',truncation=True)

In [16]:
tokenized_datasets=dataset.map(tokenize_function,batched=True)

  0%|          | 0/650 [00:00<?, ?ba/s]

  0%|          | 0/50 [00:00<?, ?ba/s]

In [17]:
tokenized_datasets['train']

Dataset({
    features: ['label', 'text', 'input_ids', 'token_type_ids', 'attention_mask'],
    num_rows: 650000
})

Consider a sample of tokenized data for training and evaluation

In [18]:
small_train=tokenized_datasets['train'].shuffle(seed=42).select(range(1000))
small_eval=tokenized_datasets['train'].shuffle(seed=42).select(range(1000))

In [19]:
small_train

Dataset({
    features: ['label', 'text', 'input_ids', 'token_type_ids', 'attention_mask'],
    num_rows: 1000
})

In [20]:
model=AutoModelForSequenceClassification.from_pretrained('bert-base-cased',num_labels=5)

Downloading:   0%|          | 0.00/436M [00:00<?, ?B/s]

Some weights of the model checkpoint at bert-base-cased were not used when initializing BertForSequenceClassification: ['cls.seq_relationship.bias', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.decoder.weight']
- This IS expected if you are initializing BertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at b

In [21]:
# dataset['train']

Training hyperparameters using trainer class

In [22]:
from transformers import TrainingArguments,Trainer
training_args=TrainingArguments(output_dir='training_args_directory')

Metrics

In [23]:
import numpy as np
from datasets import load_metric
metric = load_metric("accuracy")

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: FutureWarning: load_metric is deprecated and will be removed in the next major version of datasets. Use 'evaluate.load' instead, from the new library 🤗 Evaluate: https://huggingface.co/docs/evaluate
  This is separate from the ipykernel package so we can avoid doing imports until


In [24]:
def compute_metric(eval_preds):
  logits,eval=eval_preds
  predictions=np.argmax(logits,axis=-1)
  return metric.compute(predictions=predictions,references=eval)
  

In [25]:
training_args = TrainingArguments(output_dir="test_trainer", evaluation_strategy="epoch")

In [26]:
trainer=Trainer(
    model=model,
    args=training_args,
    train_dataset=small_train,
    eval_dataset=small_eval,
    compute_metrics=compute_metric,
    )

Trainer and training the model

In [27]:
trainer.train()

The following columns in the training set don't have a corresponding argument in `BertForSequenceClassification.forward` and have been ignored: text. If text are not expected by `BertForSequenceClassification.forward`,  you can safely ignore this message.
/usr/local/lib/python3.7/dist-packages/transformers/optimization.py:310: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  FutureWarning,
***** Running training *****
  Num examples = 1000
  Num Epochs = 3
  Instantaneous batch size per device = 8
  Total train batch size (w. parallel, distributed & accumulation) = 8
  Gradient Accumulation steps = 1
  Total optimization steps = 375


The following columns in the evaluation set don't have a corresponding argument in `BertForSequenceClassification.forward` and have been ignored: text. If text are not expected by `BertForSequenceClassification.forward`,  you can safely ignore this message.
***** Running Evaluation *****
  Num examples = 1000
  Batch size = 8
The following columns in the evaluation set don't have a corresponding argument in `BertForSequenceClassification.forward` and have been ignored: text. If text are not expected by `BertForSequenceClassification.forward`,  you can safely ignore this message.
***** Running Evaluation *****
  Num examples = 1000
  Batch size = 8
The following columns in the evaluation set don't have a corresponding argument in `BertForSequenceClassification.forward` and have been ignored: text. If text are not expected by `BertForSequenceClassification.forward`,  you can safely ignore this message.
***** Running Evaluation *****
  Num examples = 1000
  Batch size = 8


Training compl

TrainOutput(global_step=375, training_loss=1.2540281575520833, metrics={'train_runtime': 398.168, 'train_samples_per_second': 7.535, 'train_steps_per_second': 0.942, 'total_flos': 789354427392000.0, 'train_loss': 1.2540281575520833, 'epoch': 3.0})

Pytorch way to train the model

In [28]:
from torch.utils.data import DataLoader
train_dl=DataLoader(small_train,shuffle=True,batch_size=8)
eval_dl=DataLoader(small_eval,batch_size=8)

Optimizer

In [29]:
from torch.optim import AdamW
optimizer=AdamW(model.parameters(),lr=5e-5)

In [30]:
from transformers import get_scheduler
num_epochs=3
num_training_steps=num_epochs*(len(train_dl))
lr_scheduler=get_scheduler(name='linear',optimizer=optimizer,num_training_steps=num_training_steps,num_warmup_steps=0)


In [31]:
device=torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')
model.to(device)

BertForSequenceClassification(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(28996, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0): BertLayer(
          (attention): BertAttention(
            (self): BertSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, element

In [32]:
from tqdm.auto import tqdm

progress_bar = tqdm(range(num_training_steps))

model.train()


for epoch in range(num_epochs):
  for batch in train_dl:
    batch={k: v.to(device) for k,v in batch.items()}
    outputs=model(**batch)
    loss=outputs.loss
    loss.backward()

    optimizer.step()
    lr_scheduler.step()
    optimizer.zero_grad()
    progress_bar.update(1)

    

  0%|          | 0/375 [00:00<?, ?it/s]

AttributeError: ignored

In [ ]:
metric=load_metric('accuray')

model.eval()

for batch in eval_dl:
  batch={k: v.to(device) for k , v in batcg.items()}
  with torch.no_grad():
    output=model(**batch)

  logits=output.logits
  prediction=torch.argmax(logits,dim=-1)
  metric.add_batch(predictions=prediction,references=batch['labels'])

metric.compute()